### ISSUE TITLE
[bug] 400 bad request on ".model.json"

### ISSUE THREAD

**Issue by I2obiN** [adobe/aem-spa-page-model-manager#18]
**Describe the bug**
The ModelManager initializes correct on my page with "us.model.json". For some reason the aem-spa-page-model-manager then makes a request to ".model.json" a resource that can't possibly exist and gets a 400 response breaking the react application.

**Package version**
latest

**To Reproduce**
I cannot reproduce this, AEM suddenly started behaving like this

**Expected behavior**
Only validated values should be passed

**Additional context**
Page was working then suddenly was not

**Comment by pfauchere** [comment]
@I2obiN Could you please provide steps so that we can systematically reproduce the problem?

**Comment by claudiab** [comment]
Hi, I have seen this weird error come up.

**Package version**
    "@adobe/cq-spa-page-model-manager": "1.1.3",

**To Reproduce**
First spotted issue after deploying app into testing environment. Steps to see this problem locally:

1. Generate sample project  
 mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.granite.archetypes \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=23 \
 -D aemVersion=6.5.4 \
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite" \
 -D frontendModule=angular \
 -D includeExamples=y

2. Go to app-routing.module.ts:

3. Update Routes priority
   {
    path: '',
    redirectTo: enviroment.APP_ROOT_PATH,
    pathMatch: 'full',
  },
  {
    matcher: AemPageMatcher,
    component: PageComponent,
    resolve: {
      path: AemPageDataResolver,
    }
4. Add cq:pagemodel_route_filters to customheaders.html and index.html 
 < meta property="cq:pagemodel_route_filters" content="index,^(.*)(?:index)(.*)" >
5. Run mvn clean install -PautoInstallPackage from root
6. Run npm start from ui.frontend
7. Go to browser and access app from http://localhost:4200/index.html
8. App routes to http://localhost:4200/content/mysite/us/en/home.html with error from index.model.json
9.  400 errors from index.model.json break angular app

Errors: 
<img width="1440" alt="aem-double-model-error-2" src="https://user-images.githubusercontent.com/773758/94074155-5337c980-fdbe-11ea-9df8-db3861390ff3.png">
<img width="1440" alt="aem-double-model-error" src="https://user-images.githubusercontent.com/773758/94074158-5468f680-fdbe-11ea-984c-bad53e3978c9.png">

**Expected behavior**
App should automatically route from  http://localhost:4200/index.html to  http://localhost:4200/content/us/en/mysite.html and not show errors for index.model.json

This error did not come up with old package:
    "@adobe/cq-spa-page-model-manager": "1.1.3",

**Comment by grubyak** [comment]
thank you @I2obiN and @claudiab for detailed reproduction steps, we are going to work on that now.

**Comment by grubyak** [comment]
archetype generator `<=24` will still produce a buggy project, it's because:
- it relies on obsolete spa modules (before we open source them)
- embedding bundles that are already included in aem qs

we suggest following manual steps to fix the problem:
- use http://localhost:4502/system/console/bundles/ to delete duplicate bundles:
  - `com.adobe.cq.core.wcm.components.extensions.amp` (keep 2.11.1)
  - `com.adobe.cq.core.wcm.components.core` (keep 2.11.1)
  - `spa.project.core.core` (keep 1.1.2)
- use following spa modules (in `ui.frontend/package.json`) instead of `@adobe/cq-*`:
  - `@adobe/aem-angular-editable-components`
  - `@adobe/aem-spa-component-mapping`
  - `@adobe/aem-spa-page-model-manager`
- reinstall the project
- restart aem

mentioned steps won't be needed for project generated with archetype `25+`

**Comment by voghan** [comment]
Is the expected behavior to always change the location.href to appRoot for the application to load the SPA application? Our client does not want to see that after their website domain.
